
package ir.tamin.insurance.technical.business.service.info;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SsupServices", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", wsdlLocation = "http://ssuppermits.tamin.ir:4040/ssuppermits/SsupPermitsMain.asmx?WSDL")
public class SsupServices
    extends Service
{

    private final static URL SSUPSERVICES_WSDL_LOCATION;
    private final static WebServiceException SSUPSERVICES_EXCEPTION;
    private final static QName SSUPSERVICES_QNAME = new QName("http://tempuri.org/SSupPermit/SsupServices", "SsupServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ssuppermits.tamin.ir:4040/ssuppermits/SsupPermitsMain.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SSUPSERVICES_WSDL_LOCATION = url;
        SSUPSERVICES_EXCEPTION = e;
    }

    public SsupServices() {
        super(__getWsdlLocation(), SSUPSERVICES_QNAME);
    }

    public SsupServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), SSUPSERVICES_QNAME, features);
    }

    public SsupServices(URL wsdlLocation) {
        super(wsdlLocation, SSUPSERVICES_QNAME);
    }

    public SsupServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SSUPSERVICES_QNAME, features);
    }

    public SsupServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SsupServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SsupServicesSoap
     */
    @WebEndpoint(name = "SsupServicesSoap")
    public SsupServicesSoap getSsupServicesSoap() {
        return super.getPort(new QName("http://tempuri.org/SSupPermit/SsupServices", "SsupServicesSoap"), SsupServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SsupServicesSoap
     */
    @WebEndpoint(name = "SsupServicesSoap")
    public SsupServicesSoap getSsupServicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/SSupPermit/SsupServices", "SsupServicesSoap"), SsupServicesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SSUPSERVICES_EXCEPTION!= null) {
            throw SSUPSERVICES_EXCEPTION;
        }
        return SSUPSERVICES_WSDL_LOCATION;
    }

}
