
package ir.tamin.incomeBank.service.asnad.webservice.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthenticationWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationWebServiceSoap {


    /**
     * 
     * @param validateCode
     * @param userName
     * @param getValidationCodeResult
     * @param vahedCode
     * @param loginType
     * @param pass
     */
    @WebMethod(operationName = "GetValidationCode", action = "http://tempuri.org/GetValidationCode")
    @RequestWrapper(localName = "GetValidationCode", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.authentication.GetValidationCode")
    @ResponseWrapper(localName = "GetValidationCodeResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.authentication.GetValidationCodeResponse")
    public void getValidationCode(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "VahedCode", targetNamespace = "http://tempuri.org/")
        String vahedCode,
        @WebParam(name = "LoginType", targetNamespace = "http://tempuri.org/")
        String loginType,
        @WebParam(name = "Validate_Code", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> validateCode,
        @WebParam(name = "GetValidationCodeResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Boolean> getValidationCodeResult);

    /**
     * 
     * @param validateCode
     * @param vahedCode
     * @param loginType
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CheckValidationCode", action = "http://tempuri.org/CheckValidationCode")
    @WebResult(name = "CheckValidationCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckValidationCode", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.authentication.CheckValidationCode")
    @ResponseWrapper(localName = "CheckValidationCodeResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.authentication.CheckValidationCodeResponse")
    public boolean checkValidationCode(
        @WebParam(name = "VahedCode", targetNamespace = "http://tempuri.org/")
        String vahedCode,
        @WebParam(name = "Validate_Code", targetNamespace = "http://tempuri.org/")
        String validateCode,
        @WebParam(name = "LoginType", targetNamespace = "http://tempuri.org/")
        String loginType);

}
