
package ir.tamin.incomeBank.service.daramadBank.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CentralOrdRequestSoap", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CentralOrdRequestSoap {


    /**
     * 
     * @param sAccount
     * @param sDt
     * @param sRowId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "OrdRequest_Refah_old", action = "http://tempuri.org/OrdRequest/CentralOrdRequest/OrdRequest_Refah_old")
    @WebResult(name = "OrdRequest_Refah_oldResult", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
    @RequestWrapper(localName = "OrdRequest_Refah_old", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", className = "ir.tamin.incomeBank.service.daramadBank.webservice.OrdRequestRefahOld")
    @ResponseWrapper(localName = "OrdRequest_Refah_oldResponse", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", className = "ir.tamin.incomeBank.service.daramadBank.webservice.OrdRequestRefahOldResponse")
    public String ordRequestRefahOld(
        @WebParam(name = "s_Account", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
        String sAccount,
        @WebParam(name = "s_RowId", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
        String sRowId,
        @WebParam(name = "s_Dt", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
        String sDt);

    /**
     * 
     * @param sRowId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "OrdRequest_Tejarat", action = "http://tempuri.org/OrdRequest/CentralOrdRequest/OrdRequest_Tejarat")
    @WebResult(name = "OrdRequest_TejaratResult", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
    @RequestWrapper(localName = "OrdRequest_Tejarat", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", className = "ir.tamin.incomeBank.service.daramadBank.webservice.OrdRequestTejarat")
    @ResponseWrapper(localName = "OrdRequest_TejaratResponse", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", className = "ir.tamin.incomeBank.service.daramadBank.webservice.OrdRequestTejaratResponse")
    public String ordRequestTejarat(
        @WebParam(name = "s_RowId", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
        String sRowId);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "OrdRequest_Tejarat_chagepass", action = "http://tempuri.org/OrdRequest/CentralOrdRequest/OrdRequest_Tejarat_chagepass")
    @WebResult(name = "OrdRequest_Tejarat_chagepassResult", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
    @RequestWrapper(localName = "OrdRequest_Tejarat_chagepass", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", className = "ir.tamin.incomeBank.service.daramadBank.webservice.OrdRequestTejaratChagepass")
    @ResponseWrapper(localName = "OrdRequest_Tejarat_chagepassResponse", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", className = "ir.tamin.incomeBank.service.daramadBank.webservice.OrdRequestTejaratChagepassResponse")
    public boolean ordRequestTejaratChagepass();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTicketID", action = "http://tempuri.org/OrdRequest/CentralOrdRequest/GetTicketID")
    @WebResult(name = "GetTicketIDResult", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
    @RequestWrapper(localName = "GetTicketID", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetTicketID")
    @ResponseWrapper(localName = "GetTicketIDResponse", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetTicketIDResponse")
    public String getTicketID();

    /**
     * 
     * @param sAccountNo
     * @param sRowID
     * @param sDt
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "OrdRequest_Refah", action = "http://tempuri.org/OrdRequest/CentralOrdRequest/OrdRequest_Refah")
    @WebResult(name = "OrdRequest_RefahResult", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
    @RequestWrapper(localName = "OrdRequest_Refah", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", className = "ir.tamin.incomeBank.service.daramadBank.webservice.OrdRequestRefah")
    @ResponseWrapper(localName = "OrdRequest_RefahResponse", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", className = "ir.tamin.incomeBank.service.daramadBank.webservice.OrdRequestRefahResponse")
    public String ordRequestRefah(
        @WebParam(name = "s_AccountNo", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
        String sAccountNo,
        @WebParam(name = "s_RowID", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
        String sRowID,
        @WebParam(name = "s_Dt", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest")
        String sDt);

}
