package ir.tamin.incomeBank.service.daramadBank.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 *
 */
@WebServiceClient(name = "CentralOrdRequest", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", wsdlLocation = "http://172.16.1.106:8080/CentralOrdRequest.asmx?wsdl") // تستی
//@WebServiceClient(name = "CentralOrdRequest", targetNamespace = "http://tempuri.org/OrdRequest/CentralOrdRequest", wsdlLocation = "http://10.16.1.106:8080/CentralOrdRequest.asmx?wsdl")// عملیاتی
public class CentralOrdRequest
        extends Service {

    private final static URL CENTRALORDREQUEST_WSDL_LOCATION;
    private final static WebServiceException CENTRALORDREQUEST_EXCEPTION;
    private final static QName CENTRALORDREQUEST_QNAME = new QName("http://tempuri.org/OrdRequest/CentralOrdRequest", "CentralOrdRequest");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.1.106:8080/CentralOrdRequest.asmx?wsdl"); // تستی
            //url = new URL("http://10.16.1.106:8080/CentralOrdRequest.asmx?wsdl");// عملیاتی
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CENTRALORDREQUEST_WSDL_LOCATION = url;
        CENTRALORDREQUEST_EXCEPTION = e;
    }

    public CentralOrdRequest() {
        super(__getWsdlLocation(), CENTRALORDREQUEST_QNAME);
    }

    public CentralOrdRequest(WebServiceFeature... features) {
        super(__getWsdlLocation(), CENTRALORDREQUEST_QNAME, features);
    }

    public CentralOrdRequest(URL wsdlLocation) {
        super(wsdlLocation, CENTRALORDREQUEST_QNAME);
    }

    public CentralOrdRequest(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CENTRALORDREQUEST_QNAME, features);
    }

    public CentralOrdRequest(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CentralOrdRequest(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns CentralOrdRequestSoap
     */
    @WebEndpoint(name = "CentralOrdRequestSoap")
    public CentralOrdRequestSoap getCentralOrdRequestSoap() {
        return super.getPort(new QName("http://tempuri.org/OrdRequest/CentralOrdRequest", "CentralOrdRequestSoap"), CentralOrdRequestSoap.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns CentralOrdRequestSoap
     */
    @WebEndpoint(name = "CentralOrdRequestSoap")
    public CentralOrdRequestSoap getCentralOrdRequestSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/OrdRequest/CentralOrdRequest", "CentralOrdRequestSoap"), CentralOrdRequestSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CENTRALORDREQUEST_EXCEPTION != null) {
            throw CENTRALORDREQUEST_EXCEPTION;
        }
        return CENTRALORDREQUEST_WSDL_LOCATION;
    }

}
