
package ir.tamin.incomeBank.ws.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param blbcFile
     * @param blbc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendAccBillBack", action = "http://tempuri.org/SendAccBillBack")
    @WebResult(name = "SendAccBillBackResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendAccBillBack", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.SendAccBillBack")
    @ResponseWrapper(localName = "SendAccBillBackResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.SendAccBillBackResponse")
    public String sendAccBillBack(
        @WebParam(name = "blbc", targetNamespace = "http://tempuri.org/")
        BillBack blbc,
        @WebParam(name = "blbcFile", targetNamespace = "http://tempuri.org/")
        byte[] blbcFile);

    /**
     * 
     * @param newelm
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewSend", action = "http://tempuri.org/NewSend")
    @WebResult(name = "NewSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NewSend", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.NewSend")
    @ResponseWrapper(localName = "NewSendResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.NewSendResponse")
    public String newSend(
        @WebParam(name = "Newelm", targetNamespace = "http://tempuri.org/")
        NewElam newelm);

    /**
     * 
     * @param atch
     * @param newelm
     * @param binaryF
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewSendElmWithAtch", action = "http://tempuri.org/NewSendElmWithAtch")
    @WebResult(name = "NewSendElmWithAtchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NewSendElmWithAtch", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.NewSendElmWithAtch")
    @ResponseWrapper(localName = "NewSendElmWithAtchResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.NewSendElmWithAtchResponse")
    public String newSendElmWithAtch(
        @WebParam(name = "Newelm", targetNamespace = "http://tempuri.org/")
        NewElam newelm,
        @WebParam(name = "atch", targetNamespace = "http://tempuri.org/")
        Attach atch,
        @WebParam(name = "binaryF", targetNamespace = "http://tempuri.org/")
        byte[] binaryF);

    /**
     * 
     * @param atch
     * @param elm
     * @param binaryF
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewwriteBinaryFELM", action = "http://tempuri.org/NewwriteBinaryFELM")
    @WebResult(name = "NewwriteBinaryFELMResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NewwriteBinaryFELM", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.NewwriteBinaryFELM")
    @ResponseWrapper(localName = "NewwriteBinaryFELMResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.NewwriteBinaryFELMResponse")
    public String newwriteBinaryFELM(
        @WebParam(name = "binaryF", targetNamespace = "http://tempuri.org/")
        byte[] binaryF,
        @WebParam(name = "atch", targetNamespace = "http://tempuri.org/")
        Attach atch,
        @WebParam(name = "elm", targetNamespace = "http://tempuri.org/")
        NewElam elm);

    /**
     * 
     * @param snd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getSanad")
    @WebResult(name = "getSanadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getSanad", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetSanad")
    @ResponseWrapper(localName = "getSanadResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetSanadResponse")
    public String getSanad(
        @WebParam(name = "snd", targetNamespace = "http://tempuri.org/")
        Sanad snd);

    /**
     * 
     * @param ar
     * @param ramz
     * @param esk
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "req_f_r", action = "http://tempuri.org/req_f_r")
    @WebResult(name = "req_f_rResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "req_f_r", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.ReqFR")
    @ResponseWrapper(localName = "req_f_rResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.ReqFRResponse")
    public String reqFR(
        @WebParam(name = "ar", targetNamespace = "http://tempuri.org/")
        String ar,
        @WebParam(name = "ramz", targetNamespace = "http://tempuri.org/")
        String ramz,
        @WebParam(name = "esk", targetNamespace = "http://tempuri.org/")
        String esk);

    /**
     * 
     * @param bAutoInsert
     * @param voucher
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ServiceResult
     */
    @WebMethod(operationName = "SendDataToTemp", action = "http://tempuri.org/SendDataToTemp")
    @WebResult(name = "SendDataToTempResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendDataToTemp", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.SendDataToTemp")
    @ResponseWrapper(localName = "SendDataToTempResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.SendDataToTempResponse")
    public ServiceResult sendDataToTemp(
        @WebParam(name = "Voucher", targetNamespace = "http://tempuri.org/")
        AccVoucherEntity voucher,
        @WebParam(name = "bAutoInsert", targetNamespace = "http://tempuri.org/")
        boolean bAutoInsert);

    /**
     * 
     * @param strYear
     * @param bIsKar
     * @param strVahedCode
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.FinancialStatementsEntity
     */
    @WebMethod(operationName = "GetFinancialStatements", action = "http://tempuri.org/GetFinancialStatements")
    @WebResult(name = "GetFinancialStatementsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFinancialStatements", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetFinancialStatements")
    @ResponseWrapper(localName = "GetFinancialStatementsResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetFinancialStatementsResponse")
    public FinancialStatementsEntity getFinancialStatements(
        @WebParam(name = "strVahedCode", targetNamespace = "http://tempuri.org/")
        String strVahedCode,
        @WebParam(name = "strYear", targetNamespace = "http://tempuri.org/")
        String strYear,
        @WebParam(name = "bIsKar", targetNamespace = "http://tempuri.org/")
        boolean bIsKar);

    /**
     * 
     * @param strYear
     * @param bIsKar
     * @param strVahedCode
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ListRemainBankEntity
     */
    @WebMethod(operationName = "GetRemainBank", action = "http://tempuri.org/GetRemainBank")
    @WebResult(name = "GetRemainBankResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRemainBank", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetRemainBank")
    @ResponseWrapper(localName = "GetRemainBankResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetRemainBankResponse")
    public ListRemainBankEntity getRemainBank(
        @WebParam(name = "strVahedCode", targetNamespace = "http://tempuri.org/")
        String strVahedCode,
        @WebParam(name = "strYear", targetNamespace = "http://tempuri.org/")
        String strYear,
        @WebParam(name = "bIsKar", targetNamespace = "http://tempuri.org/")
        boolean bIsKar);

    /**
     * 
     * @param strYear
     * @param strVahedCode
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ListInvForm51Entity
     */
    @WebMethod(operationName = "GetInvForm5_1", action = "http://tempuri.org/GetInvForm5_1")
    @WebResult(name = "GetInvForm5_1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInvForm5_1", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetInvForm51")
    @ResponseWrapper(localName = "GetInvForm5_1Response", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetInvForm51Response")
    public ListInvForm51Entity getInvForm51(
        @WebParam(name = "strVahedCode", targetNamespace = "http://tempuri.org/")
        String strVahedCode,
        @WebParam(name = "strYear", targetNamespace = "http://tempuri.org/")
        String strYear);

    /**
     * 
     * @param strYear
     * @param bIsKar
     * @param strVahedCode
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.FinancialConfirmEntity
     */
    @WebMethod(operationName = "GetFinancialConfirm", action = "http://tempuri.org/GetFinancialConfirm")
    @WebResult(name = "GetFinancialConfirmResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFinancialConfirm", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetFinancialConfirm")
    @ResponseWrapper(localName = "GetFinancialConfirmResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetFinancialConfirmResponse")
    public FinancialConfirmEntity getFinancialConfirm(
        @WebParam(name = "strVahedCode", targetNamespace = "http://tempuri.org/")
        String strVahedCode,
        @WebParam(name = "strYear", targetNamespace = "http://tempuri.org/")
        String strYear,
        @WebParam(name = "bIsKar", targetNamespace = "http://tempuri.org/")
        boolean bIsKar);

    /**
     * 
     * @param sUrl
     * @param sUserName
     * @param sPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTokenOAM", action = "http://tempuri.org/GetTokenOAM")
    @WebResult(name = "GetTokenOAMResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTokenOAM", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetTokenOAM")
    @ResponseWrapper(localName = "GetTokenOAMResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetTokenOAMResponse")
    public String getTokenOAM(
        @WebParam(name = "sUrl", targetNamespace = "http://tempuri.org/")
        String sUrl,
        @WebParam(name = "sUserName", targetNamespace = "http://tempuri.org/")
        String sUserName,
        @WebParam(name = "sPass", targetNamespace = "http://tempuri.org/")
        String sPass);

    /**
     * 
     * @param requestEntity
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ServiceCallResult
     */
    @WebMethod(operationName = "CallRestService", action = "http://tempuri.org/CallRestService")
    @WebResult(name = "CallRestServiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CallRestService", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.CallRestService")
    @ResponseWrapper(localName = "CallRestServiceResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.CallRestServiceResponse")
    public ServiceCallResult callRestService(
        @WebParam(name = "RequestEntity", targetNamespace = "http://tempuri.org/")
        HttpsRequestEntity requestEntity);

    /**
     * 
     * @param jSonObj
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ArrayOfResponse
     */
    @WebMethod(operationName = "DeserializeObject", action = "http://tempuri.org/DeserializeObject")
    @WebResult(name = "DeserializeObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeserializeObject", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.DeserializeObject")
    @ResponseWrapper(localName = "DeserializeObjectResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.DeserializeObjectResponse")
    public ArrayOfResponse deserializeObject(
        @WebParam(name = "jSonObj", targetNamespace = "http://tempuri.org/")
        String jSonObj);

    /**
     * 
     * @param address
     * @param filename
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetFromFtp", action = "http://tempuri.org/GetFromFtp")
    @WebResult(name = "GetFromFtpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFromFtp", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetFromFtp")
    @ResponseWrapper(localName = "GetFromFtpResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetFromFtpResponse")
    public byte[] getFromFtp(
        @WebParam(name = "Address", targetNamespace = "http://tempuri.org/")
        String address,
        @WebParam(name = "filename", targetNamespace = "http://tempuri.org/")
        String filename);

    /**
     * 
     * @param address
     * @param filename
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetFromFolder", action = "http://tempuri.org/GetFromFolder")
    @WebResult(name = "GetFromFolderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFromFolder", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetFromFolder")
    @ResponseWrapper(localName = "GetFromFolderResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetFromFolderResponse")
    public byte[] getFromFolder(
        @WebParam(name = "Address", targetNamespace = "http://tempuri.org/")
        String address,
        @WebParam(name = "filename", targetNamespace = "http://tempuri.org/")
        String filename);

    /**
     * 
     * @param sMethod
     * @param sToken
     * @param sData
     * @param sUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TaminEtebarRelation", action = "http://tempuri.org/TaminEtebarRelation")
    @WebResult(name = "TaminEtebarRelationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TaminEtebarRelation", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.TaminEtebarRelation")
    @ResponseWrapper(localName = "TaminEtebarRelationResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.TaminEtebarRelationResponse")
    public String taminEtebarRelation(
        @WebParam(name = "sData", targetNamespace = "http://tempuri.org/")
        String sData,
        @WebParam(name = "sUrl", targetNamespace = "http://tempuri.org/")
        String sUrl,
        @WebParam(name = "sMethod", targetNamespace = "http://tempuri.org/")
        String sMethod,
        @WebParam(name = "sToken", targetNamespace = "http://tempuri.org/")
        String sToken);

    /**
     * 
     * @param isTahator
     * @param elm
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ServiceResult
     */
    @WebMethod(operationName = "CreateNewElamDaramad", action = "http://tempuri.org/CreateNewElamDaramad")
    @WebResult(name = "CreateNewElamDaramadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateNewElamDaramad", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.CreateNewElamDaramad")
    @ResponseWrapper(localName = "CreateNewElamDaramadResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.CreateNewElamDaramadResponse")
    public ServiceResult createNewElamDaramad(
        @WebParam(name = "elm", targetNamespace = "http://tempuri.org/")
        ElmDaramad elm,
        @WebParam(name = "isTahator", targetNamespace = "http://tempuri.org/")
        boolean isTahator);

    /**
     * 
     * @param strYear
     * @param strUnitCode
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ArrayOfFreeCheqListEntity
     */
    @WebMethod(operationName = "GetFreeCheqList", action = "http://tempuri.org/GetFreeCheqList")
    @WebResult(name = "GetFreeCheqListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFreeCheqList", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetFreeCheqList")
    @ResponseWrapper(localName = "GetFreeCheqListResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetFreeCheqListResponse")
    public ArrayOfFreeCheqListEntity getFreeCheqList(
        @WebParam(name = "strUnitCode", targetNamespace = "http://tempuri.org/")
        String strUnitCode,
        @WebParam(name = "strYear", targetNamespace = "http://tempuri.org/")
        String strYear);

    /**
     * 
     * @param year
     * @param docSequense
     * @param unitCode
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ServiceResult
     */
    @WebMethod(operationName = "ReverseDocument", action = "http://tempuri.org/ReverseDocument")
    @WebResult(name = "ReverseDocumentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReverseDocument", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.ReverseDocument")
    @ResponseWrapper(localName = "ReverseDocumentResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.ReverseDocumentResponse")
    public ServiceResult reverseDocument(
        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        String year,
        @WebParam(name = "UnitCode", targetNamespace = "http://tempuri.org/")
        String unitCode,
        @WebParam(name = "DocSequense", targetNamespace = "http://tempuri.org/")
        long docSequense);

    /**
     * 
     * @param seqDetailSequense
     * @param year
     * @param unitCode
     * @param isTemp
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ServiceResult
     */
    @WebMethod(operationName = "DeleteDocument", action = "http://tempuri.org/DeleteDocument")
    @WebResult(name = "DeleteDocumentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteDocument", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.DeleteDocument")
    @ResponseWrapper(localName = "DeleteDocumentResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.DeleteDocumentResponse")
    public ServiceResult deleteDocument(
        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        String year,
        @WebParam(name = "UnitCode", targetNamespace = "http://tempuri.org/")
        String unitCode,
        @WebParam(name = "SeqDetailSequense", targetNamespace = "http://tempuri.org/")
        long seqDetailSequense,
        @WebParam(name = "isTemp", targetNamespace = "http://tempuri.org/")
        boolean isTemp);

    /**
     * 
     * @param month
     * @param year
     * @param unitCode
     * @param isKar
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ServiceResult
     */
    @WebMethod(operationName = "GetBill", action = "http://tempuri.org/GetBill")
    @WebResult(name = "GetBillResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBill", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetBill")
    @ResponseWrapper(localName = "GetBillResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.GetBillResponse")
    public ServiceResult getBill(
        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        String year,
        @WebParam(name = "UnitCode", targetNamespace = "http://tempuri.org/")
        String unitCode,
        @WebParam(name = "month", targetNamespace = "http://tempuri.org/")
        int month,
        @WebParam(name = "isKar", targetNamespace = "http://tempuri.org/")
        boolean isKar);

    /**
     * 
     * @param unknowElam
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ServiceResult
     */
    @WebMethod(operationName = "SendUnknowElam", action = "http://tempuri.org/SendUnknowElam")
    @WebResult(name = "SendUnknowElamResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendUnknowElam", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.SendUnknowElam")
    @ResponseWrapper(localName = "SendUnknowElamResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.SendUnknowElamResponse")
    public ServiceResult sendUnknowElam(
        @WebParam(name = "_unknowElam", targetNamespace = "http://tempuri.org/")
        UnknowElam unknowElam);

    /**
     * 
     * @param year
     * @param unitCode
     * @param isSend
     * @param id
     * @param status
     * @return
     *     returns ir.tamin.incomeBank.ws.soap.ServiceResult
     */
    @WebMethod(operationName = "UpdateUnknowElamStatus", action = "http://tempuri.org/UpdateUnknowElamStatus")
    @WebResult(name = "UpdateUnknowElamStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUnknowElamStatus", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.UpdateUnknowElamStatus")
    @ResponseWrapper(localName = "UpdateUnknowElamStatusResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.ws.soap.UpdateUnknowElamStatusResponse")
    public ServiceResult updateUnknowElamStatus(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        long id,
        @WebParam(name = "status", targetNamespace = "http://tempuri.org/")
        String status,
        @WebParam(name = "unitCode", targetNamespace = "http://tempuri.org/")
        String unitCode,
        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        String year,
        @WebParam(name = "isSend", targetNamespace = "http://tempuri.org/")
        boolean isSend);

}
