package ir.tamin.incomeBank.service.asnad.webservice.brefah;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 *
 */
@WebServiceClient(name = "BRefahWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://darman-refah.ssodc.ir:8080/webservice/BrefahWebservice.asmx?wsdl")
//@WebServiceClient(name = "BRefahWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://http://172.16.15.48:8080/webservice/BrefahWebservice.asmx?wsdl")
public class BRefahWebService
        extends Service {

    private final static URL BREFAHWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException BREFAHWEBSERVICE_EXCEPTION;
    private final static QName BREFAHWEBSERVICE_QNAME = new QName("http://tempuri.org/", "BRefahWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://darman-refah.ssodc.ir:8080/webservice/BrefahWebservice.asmx?wsdl");
//            url = new URL("http://172.16.15.48:8080/webservice/BrefahWebservice.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BREFAHWEBSERVICE_WSDL_LOCATION = url;
        BREFAHWEBSERVICE_EXCEPTION = e;
    }

    public BRefahWebService() {
        super(__getWsdlLocation(), BREFAHWEBSERVICE_QNAME);
    }

    public BRefahWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BREFAHWEBSERVICE_QNAME, features);
    }

    public BRefahWebService(URL wsdlLocation) {
        super(wsdlLocation, BREFAHWEBSERVICE_QNAME);
    }

    public BRefahWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BREFAHWEBSERVICE_QNAME, features);
    }

    public BRefahWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BRefahWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns BRefahWebServiceSoap
     */
    @WebEndpoint(name = "BRefahWebServiceSoap")
    public BRefahWebServiceSoap getBRefahWebServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "BRefahWebServiceSoap"), BRefahWebServiceSoap.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns BRefahWebServiceSoap
     */
    @WebEndpoint(name = "BRefahWebServiceSoap")
    public BRefahWebServiceSoap getBRefahWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BRefahWebServiceSoap"), BRefahWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BREFAHWEBSERVICE_EXCEPTION != null) {
            throw BREFAHWEBSERVICE_EXCEPTION;
        }
        return BREFAHWEBSERVICE_WSDL_LOCATION;
    }

}
