
package ir.tamin.incomeBank.service.asnad.webservice.brefah;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BRefahWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BRefahWebServiceSoap {


    /**
     * Drug_ShenadeDarService
     * 
     * @param payAccReq
     * @return
     *     returns ir.tamin.incomeBank.service.asnad.webservice.brefah.PaymentAccountResultRefah
     */
    @WebMethod(operationName = "Shenasedar_InsertDrugPaymentAccount", action = "http://tempuri.org/Shenasedar_InsertDrugPaymentAccount")
    @WebResult(name = "Shenasedar_InsertDrugPaymentAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Shenasedar_InsertDrugPaymentAccount", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.brefah.ShenasedarInsertDrugPaymentAccount")
    @ResponseWrapper(localName = "Shenasedar_InsertDrugPaymentAccountResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.brefah.ShenasedarInsertDrugPaymentAccountResponse")
    public PaymentAccountResultRefah shenasedarInsertDrugPaymentAccount(
        @WebParam(name = "PayAccReq", targetNamespace = "http://tempuri.org/")
        PaymentAccountRequestRefah payAccReq);

    /**
     * Drug_ShenadeDarService_Portal
     * 
     * @param message
     * @param payAccReq
     * @param shenasedarInsertDrugPaymentAccountAsnadResult
     */
    @WebMethod(operationName = "Shenasedar_InsertDrugPaymentAccount_Asnad", action = "http://tempuri.org/Shenasedar_InsertDrugPaymentAccount_Asnad")
    @RequestWrapper(localName = "Shenasedar_InsertDrugPaymentAccount_Asnad", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.brefah.ShenasedarInsertDrugPaymentAccountAsnad")
    @ResponseWrapper(localName = "Shenasedar_InsertDrugPaymentAccount_AsnadResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.brefah.ShenasedarInsertDrugPaymentAccountAsnadResponse")
    public void shenasedarInsertDrugPaymentAccountAsnad(
        @WebParam(name = "PayAccReq", targetNamespace = "http://tempuri.org/")
        PaymentAccountRequestPortal payAccReq,
        @WebParam(name = "Message", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> message,
        @WebParam(name = "Shenasedar_InsertDrugPaymentAccount_AsnadResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Boolean> shenasedarInsertDrugPaymentAccountAsnadResult);

    /**
     * ShenadeDarService
     * 
     * @param payAccReq
     * @return
     *     returns ir.tamin.incomeBank.service.asnad.webservice.brefah.PaymentAccountResultRefah
     */
    @WebMethod(operationName = "Shenasedar_InsertPaymentAccount", action = "http://tempuri.org/Shenasedar_InsertPaymentAccount")
    @WebResult(name = "Shenasedar_InsertPaymentAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Shenasedar_InsertPaymentAccount", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.brefah.ShenasedarInsertPaymentAccount")
    @ResponseWrapper(localName = "Shenasedar_InsertPaymentAccountResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.brefah.ShenasedarInsertPaymentAccountResponse")
    public PaymentAccountResultRefah shenasedarInsertPaymentAccount(
        @WebParam(name = "PayAccReq", targetNamespace = "http://tempuri.org/")
        PaymentAccountRequestRefah payAccReq);

    /**
     * PaymentTransfer
     * 
     * @param requestTran
     * @return
     *     returns ir.tamin.incomeBank.service.asnad.webservice.brefah.ResultTransfer
     */
    @WebMethod(operationName = "Shenasedar_PaymentTransfer", action = "http://tempuri.org/Shenasedar_PaymentTransfer")
    @WebResult(name = "Shenasedar_PaymentTransferResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Shenasedar_PaymentTransfer", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.brefah.ShenasedarPaymentTransfer")
    @ResponseWrapper(localName = "Shenasedar_PaymentTransferResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.brefah.ShenasedarPaymentTransferResponse")
    public ResultTransfer shenasedarPaymentTransfer(
        @WebParam(name = "RequestTran", targetNamespace = "http://tempuri.org/")
        RequestTransfer requestTran);

    /**
     * Search_PaymentTransfer
     * 
     * @param shenasePayment
     * @return
     *     returns ir.tamin.incomeBank.service.asnad.webservice.brefah.ResultSearchTransfer
     */
    @WebMethod(operationName = "Shenasedar_SearchPaymentTransfer", action = "http://tempuri.org/Shenasedar_SearchPaymentTransfer")
    @WebResult(name = "Shenasedar_SearchPaymentTransferResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Shenasedar_SearchPaymentTransfer", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.brefah.ShenasedarSearchPaymentTransfer")
    @ResponseWrapper(localName = "Shenasedar_SearchPaymentTransferResponse", targetNamespace = "http://tempuri.org/", className = "ir.tamin.incomeBank.service.asnad.webservice.brefah.ShenasedarSearchPaymentTransferResponse")
    public ResultSearchTransfer shenasedarSearchPaymentTransfer(
        @WebParam(name = "ShenasePayment", targetNamespace = "http://tempuri.org/")
        String shenasePayment);

}
