
package ir.tamin.insurance.technical.business.service.info;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SsupServicesSoap", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SsupServicesSoap {


    /**
     * 
     * @param sToday
     * @param sBrchCode
     * @return
     *     returns ir.tamin.insurance.technical.business.service.info.ArrayOfClsPermitSpec
     */
    @WebMethod(operationName = "GetSsupPermit", action = "http://tempuri.org/SSupPermit/SsupServices/GetSsupPermit")
    @WebResult(name = "GetSsupPermitResult", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
    @RequestWrapper(localName = "GetSsupPermit", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", className = "ir.tamin.insurance.technical.business.service.info.GetSsupPermit")
    @ResponseWrapper(localName = "GetSsupPermitResponse", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", className = "ir.tamin.insurance.technical.business.service.info.GetSsupPermitResponse")
    public ArrayOfClsPermitSpec getSsupPermit(
        @WebParam(name = "sToday", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sToday,
        @WebParam(name = "sBrchCode", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sBrchCode);

    /**
     * 
     * @param sToday
     * @param sBrchCode
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "SetPermit_ReciveState", action = "http://tempuri.org/SSupPermit/SsupServices/SetPermit_ReciveState")
    @WebResult(name = "SetPermit_ReciveStateResult", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
    @RequestWrapper(localName = "SetPermit_ReciveState", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", className = "ir.tamin.insurance.technical.business.service.info.SetPermitReciveState")
    @ResponseWrapper(localName = "SetPermit_ReciveStateResponse", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", className = "ir.tamin.insurance.technical.business.service.info.SetPermitReciveStateResponse")
    public Object setPermitReciveState(
        @WebParam(name = "sToday", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sToday,
        @WebParam(name = "sBrchCode", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sBrchCode);

    /**
     * 
     * @param sRisuid
     * @param sFundCode
     * @param sBrchCode
     * @return
     *     returns ir.tamin.insurance.technical.business.service.info.ArrayOfClsEntPayStatusIst
     */
    @WebMethod(operationName = "GetEnt_PayStatus_Ist", action = "http://tempuri.org/SSupPermit/SsupServices/GetEnt_PayStatus_Ist")
    @WebResult(name = "GetEnt_PayStatus_IstResult", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
    @RequestWrapper(localName = "GetEnt_PayStatus_Ist", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", className = "ir.tamin.insurance.technical.business.service.info.GetEntPayStatusIst")
    @ResponseWrapper(localName = "GetEnt_PayStatus_IstResponse", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", className = "ir.tamin.insurance.technical.business.service.info.GetEntPayStatusIstResponse")
    public ArrayOfClsEntPayStatusIst getEntPayStatusIst(
        @WebParam(name = "sRisuid", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sRisuid,
        @WebParam(name = "sFundCode", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sFundCode,
        @WebParam(name = "sBrchCode", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sBrchCode);

    /**
     * 
     * @param sRisuid
     * @param sFundCode
     * @param sBrchCode
     * @return
     *     returns ir.tamin.insurance.technical.business.service.info.ArrayOfClsEntPayStatusIst
     */
    @WebMethod(operationName = "GetEnt_PayStatus_Fund", action = "http://tempuri.org/SSupPermit/SsupServices/GetEnt_PayStatus_Fund")
    @WebResult(name = "GetEnt_PayStatus_FundResult", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
    @RequestWrapper(localName = "GetEnt_PayStatus_Fund", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", className = "ir.tamin.insurance.technical.business.service.info.GetEntPayStatusFund")
    @ResponseWrapper(localName = "GetEnt_PayStatus_FundResponse", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", className = "ir.tamin.insurance.technical.business.service.info.GetEntPayStatusFundResponse")
    public ArrayOfClsEntPayStatusIst getEntPayStatusFund(
        @WebParam(name = "sRisuid", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sRisuid,
        @WebParam(name = "sFundCode", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sFundCode,
        @WebParam(name = "sBrchCode", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sBrchCode);

    /**
     * 
     * @param sRisuid
     * @param sFundCode
     * @param sBrchCode
     * @return
     *     returns ir.tamin.insurance.technical.business.service.info.ArrayOfClsEntPayStatusIst
     */
    @WebMethod(operationName = "GetEnt_PayStatus_Cash", action = "http://tempuri.org/SSupPermit/SsupServices/GetEnt_PayStatus_Cash")
    @WebResult(name = "GetEnt_PayStatus_CashResult", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
    @RequestWrapper(localName = "GetEnt_PayStatus_Cash", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", className = "ir.tamin.insurance.technical.business.service.info.GetEntPayStatusCash")
    @ResponseWrapper(localName = "GetEnt_PayStatus_CashResponse", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices", className = "ir.tamin.insurance.technical.business.service.info.GetEntPayStatusCashResponse")
    public ArrayOfClsEntPayStatusIst getEntPayStatusCash(
        @WebParam(name = "sRisuid", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sRisuid,
        @WebParam(name = "sFundCode", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sFundCode,
        @WebParam(name = "sBrchCode", targetNamespace = "http://tempuri.org/SSupPermit/SsupServices")
        String sBrchCode);

}
