
package ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CentralAccountSoap", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
@XmlSeeAlso({
    ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount.ObjectFactory.class
})
public interface CentralAccountSoap {


    /**
     * 
     * @param vSORATCOMMENT
     * @param vSORATRETU
     * @param vCREATEDT
     * @param vSORATMANDEH
     * @param vSORATRCVTYPE
     * @param vSORATSTAT
     * @param vEDITUID
     * @param vSORATORDPAY
     * @param vSORATMDATE
     * @param vSORATRCVNO
     * @param vSORATPRICE2
     * @param vSORATPRICE1
     * @param vSORATEFDATE
     * @param vEDITDT
     * @param vSORATROWH
     * @param vSORATDESC
     * @param vSORATBANK
     * @param vSORATDATE
     * @param vSORATATTRIB
     * @param vCREATEUID
     * @param vSORATPASS
     * @param vSORATRADIF
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSorat", action = "http://tempuri.org/Sorat/CentralAccount/SendSorat")
    @WebResult(name = "SendSoratResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "SendSorat", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendSorat")
    @ResponseWrapper(localName = "SendSoratResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendSoratResponse")
    public String sendSorat(
        @WebParam(name = "vSORAT_DATE", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATDATE,
        @WebParam(name = "vSORAT_ORDPAY", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATORDPAY,
        @WebParam(name = "vSORAT_RCVTYPE", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATRCVTYPE,
        @WebParam(name = "vSORAT_RCVNO", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATRCVNO,
        @WebParam(name = "vSORAT_ATTRIB", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATATTRIB,
        @WebParam(name = "vSORAT_MDATE", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATMDATE,
        @WebParam(name = "vSORAT_RETU", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATRETU,
        @WebParam(name = "vSORAT_PASS", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATPASS,
        @WebParam(name = "vSORAT_COMMENT", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATCOMMENT,
        @WebParam(name = "vCREATEUID", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vCREATEUID,
        @WebParam(name = "vCREATEDT", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vCREATEDT,
        @WebParam(name = "vSORAT_RADIF", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATRADIF,
        @WebParam(name = "vSORAT_MANDEH", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        double vSORATMANDEH,
        @WebParam(name = "vEDITUID", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vEDITUID,
        @WebParam(name = "vEDITDT", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vEDITDT,
        @WebParam(name = "vSORAT_BANK", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATBANK,
        @WebParam(name = "vSORAT_PRICE1", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        double vSORATPRICE1,
        @WebParam(name = "vSORAT_PRICE2", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        double vSORATPRICE2,
        @WebParam(name = "vSORAT_DESC", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATDESC,
        @WebParam(name = "vSORAT_ROWH", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        int vSORATROWH,
        @WebParam(name = "vSORAT_STAT", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATSTAT,
        @WebParam(name = "vSORAT_EFDATE", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String vSORATEFDATE);

    /**
     * 
     * @param brchcode
     * @param price
     * @param crdDate
     * @param rcvno
     * @param rcvtype
     * @param ordpay
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDrmd_Card", action = "http://tempuri.org/Sorat/CentralAccount/GetDrmd_Card")
    @WebResult(name = "GetDrmd_CardResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "GetDrmd_Card", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetDrmdCard")
    @ResponseWrapper(localName = "GetDrmd_CardResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetDrmdCardResponse")
    public String getDrmdCard(
        @WebParam(name = "brchcode", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String brchcode,
        @WebParam(name = "ordpay", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String ordpay,
        @WebParam(name = "rcvno", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String rcvno,
        @WebParam(name = "price", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String price,
        @WebParam(name = "crd_date", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String crdDate,
        @WebParam(name = "rcvtype", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String rcvtype);

    /**
     * 
     * @param brchcode
     * @param price
     * @param crdDate
     * @param rcvno
     * @param rcvtype
     * @param ordpay
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDrmd_Sorat", action = "http://tempuri.org/Sorat/CentralAccount/GetDrmd_Sorat")
    @WebResult(name = "GetDrmd_SoratResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "GetDrmd_Sorat", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetDrmdSorat")
    @ResponseWrapper(localName = "GetDrmd_SoratResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetDrmdSoratResponse")
    public String getDrmdSorat(
        @WebParam(name = "brchcode", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String brchcode,
        @WebParam(name = "ordpay", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String ordpay,
        @WebParam(name = "rcvno", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String rcvno,
        @WebParam(name = "price", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String price,
        @WebParam(name = "crd_date", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String crdDate,
        @WebParam(name = "rcvtype", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String rcvtype);

    /**
     * 
     * @param brchcode
     * @param bnkhesab
     * @param bnkcode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRadif_Bank", action = "http://tempuri.org/Sorat/CentralAccount/GetRadif_Bank")
    @WebResult(name = "GetRadif_BankResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "GetRadif_Bank", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetRadifBank")
    @ResponseWrapper(localName = "GetRadif_BankResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetRadifBankResponse")
    public String getRadifBank(
        @WebParam(name = "brchcode", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String brchcode,
        @WebParam(name = "bnkcode", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String bnkcode,
        @WebParam(name = "bnkhesab", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String bnkhesab);

    /**
     * 
     * @param oclsletter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetLetter", action = "http://tempuri.org/Sorat/CentralAccount/SetLetter")
    @WebResult(name = "SetLetterResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "SetLetter", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SetLetter")
    @ResponseWrapper(localName = "SetLetterResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SetLetterResponse")
    public String setLetter(
        @WebParam(name = "oclsletter", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
                ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount.Clsletter oclsletter);

    /**
     * 
     * @param oclsletter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Insert_Letter", action = "http://tempuri.org/Sorat/CentralAccount/Insert_Letter")
    @WebResult(name = "Insert_LetterResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "Insert_Letter", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.InsertLetter")
    @ResponseWrapper(localName = "Insert_LetterResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.InsertLetterResponse")
    public String insertLetter(
        @WebParam(name = "oclsletter", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
                ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount.Clsletter oclsletter);

    /**
     * 
     * @param brchcode
     * @param ordpay
     * @param serial
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Send_Ok", action = "http://tempuri.org/Sorat/CentralAccount/Send_Ok")
    @WebResult(name = "Send_OkResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "Send_Ok", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendOk")
    @ResponseWrapper(localName = "Send_OkResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendOkResponse")
    public String sendOk(
        @WebParam(name = "brchcode", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String brchcode,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String serial,
        @WebParam(name = "ordpay", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String ordpay);

    /**
     * 
     * @param oclsletter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Send_Letter", action = "http://tempuri.org/Sorat/CentralAccount/Send_Letter")
    @WebResult(name = "Send_LetterResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "Send_Letter", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetter")
    @ResponseWrapper(localName = "Send_LetterResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterResponse")
    public String sendLetter(
        @WebParam(name = "oclsletter", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
                ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount.Clsletter oclsletter);

    /**
     * 
     * @param brchcode
     * @param edate
     * @param sdate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDrmd_Amar", action = "http://tempuri.org/Sorat/CentralAccount/GetDrmd_Amar")
    @WebResult(name = "GetDrmd_AmarResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "GetDrmd_Amar", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetDrmdAmar")
    @ResponseWrapper(localName = "GetDrmd_AmarResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetDrmdAmarResponse")
    public String getDrmdAmar(
        @WebParam(name = "brchcode", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String brchcode,
        @WebParam(name = "sdate", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String sdate,
        @WebParam(name = "edate", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String edate);

    /**
     * 
     * @param brchcode
     * @param edate
     * @param sdate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDrmd_AmarKol", action = "http://tempuri.org/Sorat/CentralAccount/GetDrmd_AmarKol")
    @WebResult(name = "GetDrmd_AmarKolResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "GetDrmd_AmarKol", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetDrmdAmarKol")
    @ResponseWrapper(localName = "GetDrmd_AmarKolResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetDrmdAmarKolResponse")
    public String getDrmdAmarKol(
        @WebParam(name = "brchcode", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String brchcode,
        @WebParam(name = "sdate", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String sdate,
        @WebParam(name = "edate", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String edate);

    /**
     * 
     * @param oclsletter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Send_Letter_New", action = "http://tempuri.org/Sorat/CentralAccount/Send_Letter_New")
    @WebResult(name = "Send_Letter_NewResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "Send_Letter_New", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterNew")
    @ResponseWrapper(localName = "Send_Letter_NewResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterNewResponse")
    public String sendLetterNew(
        @WebParam(name = "oclsletter", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
                ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount.Clsletter oclsletter);

    /**
     * 
     * @param oclsletter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Send_Letter_Log", action = "http://tempuri.org/Sorat/CentralAccount/Send_Letter_Log")
    @WebResult(name = "Send_Letter_LogResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "Send_Letter_Log", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterLog")
    @ResponseWrapper(localName = "Send_Letter_LogResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterLogResponse")
    public String sendLetterLog(
        @WebParam(name = "oclsletter", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
                ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount.Clsletter oclsletter);

    /**
     * 
     * @param oclsLetterN
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Send_LetterN", action = "http://tempuri.org/Sorat/CentralAccount/Send_LetterN")
    @WebResult(name = "Send_LetterNResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "Send_LetterN", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterN")
    @ResponseWrapper(localName = "Send_LetterNResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterNResponse")
    public String sendLetterN(
        @WebParam(name = "oclsLetterN", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
                ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount.ClsLetterN oclsLetterN);

    /**
     * 
     * @param brchCode
     * @param mafasaNo
     * @param rcntDat
     * @param rcontractfee
     * @param rcntNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMafasaInfo", action = "http://tempuri.org/Sorat/CentralAccount/GetMafasaInfo")
    @WebResult(name = "GetMafasaInfoResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "GetMafasaInfo", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetMafasaInfo")
    @ResponseWrapper(localName = "GetMafasaInfoResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.GetMafasaInfoResponse")
    public String getMafasaInfo(
        @WebParam(name = "brchCode", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String brchCode,
        @WebParam(name = "mafasaNo", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String mafasaNo,
        @WebParam(name = "rcntNo", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String rcntNo,
        @WebParam(name = "rcntDat", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String rcntDat,
        @WebParam(name = "rcontractfee", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
        String rcontractfee);

    /**
     * 
     * @param oclsletter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Send_LetterGno", action = "http://tempuri.org/Sorat/CentralAccount/Send_LetterGno")
    @WebResult(name = "Send_LetterGnoResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "Send_LetterGno", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterGno")
    @ResponseWrapper(localName = "Send_LetterGnoResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterGnoResponse")
    public String sendLetterGno(
        @WebParam(name = "oclsletter", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
                ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount.Clsletter oclsletter);

    /**
     * 
     * @param oclsletter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Send_Letter_NewGno", action = "http://tempuri.org/Sorat/CentralAccount/Send_Letter_NewGno")
    @WebResult(name = "Send_Letter_NewGnoResult", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
    @RequestWrapper(localName = "Send_Letter_NewGno", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterNewGno")
    @ResponseWrapper(localName = "Send_Letter_NewGnoResponse", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", className = "ir.tamin.incomeBank.service.daramadBank.webservice.SendLetterNewGnoResponse")
    public String sendLetterNewGno(
        @WebParam(name = "oclsletter", targetNamespace = "http://tempuri.org/Sorat/CentralAccount")
                ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount.Clsletter oclsletter);

}
