
package ir.tamin.incomeBank.service.daramadBank.webservice.centralAccount;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CentralAccount", targetNamespace = "http://tempuri.org/Sorat/CentralAccount", wsdlLocation = "http://172.16.1.18:4040/Sorat/CentralAccount.asmx")//file:/C:/Users/s_maknooni/AppData/Local/Temp/tempdir8902185063911860904.tmp/CentralAccount_1.wsdl")
public class CentralAccount
    extends Service
{

    private final static URL CENTRALACCOUNT_WSDL_LOCATION;
    private final static WebServiceException CENTRALACCOUNT_EXCEPTION;
    private final static QName CENTRALACCOUNT_QNAME = new QName("http://tempuri.org/Sorat/CentralAccount", "CentralAccount");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.1.18:4040/Sorat/CentralAccount.asmx ");//"file:/C:/Users/s_maknooni/AppData/Local/Temp/tempdir8902185063911860904.tmp/CentralAccount_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CENTRALACCOUNT_WSDL_LOCATION = url;
        CENTRALACCOUNT_EXCEPTION = e;
    }

    public CentralAccount() {
        super(__getWsdlLocation(), CENTRALACCOUNT_QNAME);
    }

    public CentralAccount(WebServiceFeature... features) {
        super(__getWsdlLocation(), CENTRALACCOUNT_QNAME, features);
    }

    public CentralAccount(URL wsdlLocation) {
        super(wsdlLocation, CENTRALACCOUNT_QNAME);
    }

    public CentralAccount(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CENTRALACCOUNT_QNAME, features);
    }

    public CentralAccount(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CentralAccount(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CentralAccountSoap
     */
    @WebEndpoint(name = "CentralAccountSoap")
    public CentralAccountSoap getCentralAccountSoap() {
        return super.getPort(new QName("http://tempuri.org/Sorat/CentralAccount", "CentralAccountSoap"), CentralAccountSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CentralAccountSoap
     */
    @WebEndpoint(name = "CentralAccountSoap")
    public CentralAccountSoap getCentralAccountSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/Sorat/CentralAccount", "CentralAccountSoap"), CentralAccountSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CENTRALACCOUNT_EXCEPTION!= null) {
            throw CENTRALACCOUNT_EXCEPTION;
        }
        return CENTRALACCOUNT_WSDL_LOCATION;
    }

}
