export const environment = {

  production: false,
  accessToken: 'access_token',
  expiresIn: 'expires_in',
  redirectUrl: 'http://172.16.13.178:4200',
  baseUrl: 'localhost:4200',
  authenticationEndpoint: 'http://account-test.tamin.ir:9090/auth/server/authorize',
  verifyEndpoint: '',
  logoutUrl: 'http://account-test.tamin.ir:9090/auth/signout',
  responseType: 'token',
  clientId: 'centralized-pension-js',
  getUserNameUrl: 'http://172.16.13.176:7001/eservices/api/users/current-user',
  restTimeout: 30000,
  baseurl_base: 'http://172.16.13.176:7001/erequest/api',
  baseurl_sso: 'http://172.16.13.176:7001/erequest/api',
  baseurl_stp: 'http://e-dashab2.tamin.org:7001/self-service/api',
  baseurl_gov: 'http://172.16.13.176:7001/api',
  baseurl_sabeghe2: 'http://172.16.13.176:7001/history-objection/api',
  baseurl_eblagh2: 'http://172.16.13.176:7001/announcement/api',
  baseurl_baje: 'http://172.16.13.164:7001/insurance-list/api',
  baseurl_account: 'http://account-test.tamin.ir:9091/portal/api',
  // baseurl_list: 'http://l_eivazi_pc.tamin.org:7001/electroniclist/api',
  baseurl_list: 'https://eservices-test.tamin.ir/electroniclist/api',
  baseurl_ep: 'https://ep.tamin.ir/api',
  baseurl_audit: 'http://172.16.11.51:7001/audit/api',
  theme: 'theme-web'


  /*production: false,
  accessToken: 'access_token',
  expiresIn: 'expires_in',
  redirectUrl: 'http://172.16.13.178:4200',
  baseUrl: 'http://localhost:4200',
  authenticationEndpoint: 'https://account.tamin.ir/auth/server/authorize',
  verifyEndpoint: '',
  logoutUrl: 'https://account.tamin.ir/auth/signout?redirect_uri=localhost:4200/',
  responseType: 'token',
  clientId: 'centralized-pension-js',
  getUserNameUrl: 'https://eservices.tamin.ir/api/users/current-user',

  restTimeout: 30000,
  baseurl_base: 'https://eservices.tamin.ir/api',
  baseurl_sso: 'https:///eservices-sso.tamin.ir/api',
  baseurl_stp: 'http://m-shabanlou.tamin.org:7001/erequest/api',
  baseurl_gov: 'https://eservices.tamin-test.ir/api',
  baseurl_sabeghe2: 'https://sabeghe.tamin.ir/api',
  baseurl_baje: 'http://172.16.13.164:7001/insurance-list/api',
  baseurl_account: 'https://me.tamin.ir/api',
  baseurl_audit: 'http://172.16.11.51:7001/audit/api',
  baseurl_ep: 'https://ep.tamin.ir/api',
  baseurl_list: 'http://l_eivazi_pc.tamin.org:7001/electroniclist/api',
  theme: 'theme-web'*/
};
